### ISSUE TITLE
Instructions are incomplete?

### ISSUE THREAD

**Issue by RTimothyEdwards** [efabless/volare#13]
I followed the instructions and did `python3 -m pip install --upgrade --no-cache-dir volare`, but I do not get any executable or script called "volare" that can be run from the command line.

**Comment by donn** [comment]
@RTimothyEdwards pip would have alerted you that you likely have its binary directory missing from PATH. Run the command again and you should see a warning along these lines:

![image](https://user-images.githubusercontent.com/12652988/181764102-1874feec-efa9-410e-bea4-9e0c2b50ee3c.png)

**Comment by donn** [comment]
You can also just invoke `python3 -m volare` if you don't wanna bother

**Comment by RTimothyEdwards** [comment]
The

**Comment by RTimothyEdwards** [comment]
The `python3 -m volare` doesn't work where `volare` is invoked from within caravel_user_project, for example.

Please consider adding to the instructions a comment about where `volare` will end up by default, as that was not clear to me at all.  Would running `sudo ...  pip install` have a different behavior?

**Comment by donn** [comment]
`sudo` would indeed have a different behavior. I'll update the docs.

**Comment by donn** [comment]
Resolved with #18
