### ISSUE TITLE
Enable use of PDKs other than sky130

### ISSUE THREAD

**Issue by donn** [efabless/volare#17]
Currently, it exists in an undocumented capacity. This is blocked on an open_pdks issue, but should be surfaced as soon as humanly possible.

UPDATE: 2022-09-21: There is no longer a blocker in `open_pdks`. What is left is for the OpenLane CI to be updated to have the exact same behavior as sky130 for GF180MCU.

Additionally, volare's documentation has to be updated.

**Comment by proppy** [comment]
@donn can you link the open_pdks issue that's blocking this?

**Comment by proppy** [comment]
As commented by @donn in https://github.com/efabless/volare/pull/20#issuecomment-1241737557, automation would also need to happen in OpenLane to publish alternative builds (ex: GF180MCU)

**Comment by maliberty** [comment]
@donn would you please update?  Proppy's question is 12 days old...

**Comment by proppy** [comment]
added https://github.com/The-OpenROAD-Project/OpenLane/issues/1377 on the OpenLane side to track the workflow change that need to happen.

**Comment by proppy** [comment]
I think that's done since we now have https://github.com/efabless/volare/releases/tag/gf180mcu-120b0bd69c745825a0b8b76f364043a1cd08bb6a pre-release

**Comment by donn** [comment]
You are correct- just slipped my mind. Thanks
