### ISSUE TITLE
volare cannot find gf180

### ISSUE THREAD

**Issue by thesourcerer8** [efabless/volare#38]
volare ls-remote --pdk gf180mcu
gives
Pre-built gf180mcu PDK versions                               
and then no further output.
One guess I have is that the request to GitHub to retrieve the list only gets the first few entries?
I have installed volare 0.4.3 from pip:
Requirement already satisfied: volare in ./.local/lib/python3.10/site-packages (0.4.3)
Perhaps that version is too old? In that case, please update the pip package.

**Comment by thesourcerer8** [comment]
It seems the problem is only affecting the ls-remote command, I heard that the other commands can successfully download the gf180mcu PDK

**Comment by donn** [comment]
Volare 0.4.3 is too old. The latest version on PIP is 0.6.2 (https://pypi.org/project/volare/) so I'm not 100% sure what you're talking about.

**Comment by thesourcerer8** [comment]
Ok, I upgraded to 0.6.2, but I still don't see any gf180mcu PDK versions.

**Comment by donn** [comment]
probably an API pagination issue- ill take a look on Sunday

**Comment by atorkmabrains** [comment]
@donn Any update?

**Comment by andrsmllr** [comment]
I can see the same issue. If you are using openlane a workaround is to run "PDK=gf180mcuA make pdk" in the openlane root directory, which will use volare to fetch the pre-build gf180mcu PDK required by openlane.

**Comment by proppy** [comment]
> probably an API pagination issue- ill take a look on Sunday

@donn spot on, see https://github.com/orgs/community/discussions/21901 and https://github.com/community/community/discussions/8226

doing something like https://github.com/efabless/volare/commit/3c5077a9a8cc6b2f1d22609f5227a15ae0ba83ff to fetch more result per page can workaround the issue https://github.com/efabless/volare/commit/3c5077a9a8cc6b2f1d22609f5227a15ae0ba83ff, but a proper fix would be to find a way to sort fetch all the pages and have volare sort them.
