### ISSUE TITLE
share release infra for open_pdks/sky130A

### ISSUE THREAD

**Issue by proppy** [efabless/volare#4]
Looking at https://github.com/efabless/volare/blob/a73950436109a27048c68bcd4252214694547b95/volare/common.py#L110 it seems that the PDK tarballs are fetched from https://github.com/efabless/volare/releases, but I couldn't find the corresponding workflow that publish thoose tarball in https://github.com/efabless/volare/blob/main/.github/workflows/ci.yml

As @donn pointed out in https://github.com/efabless/volare/issues/3#issuecomment-1086962891, there are conda packages for `open_pdks.sky130a` with nightly builds: https://anaconda.org/LiteX-Hub/open_pdks.sky130a/files, and the resulting tarball can be consumed without conda using something like:
```
curl -L --silent https://anaconda.org/LiteX-Hub/open_pdks.sky130a/1.0.304_0_g1491dd7/download/noarch/open_pdks.sky130a-1.0.304_0_g1491dd7-20220330_123635.tar.bz2 | tar --strip-components=2 -C $PDK_ROOT -xvjf  - share/pdk/
```

Curious if you think there would be advantes to share a common release infra for open_pdks/sky130A?

**Comment by donn** [comment]
I actually think that's a good idea. Can you link me to your CI infrastructure?

**Comment by proppy** [comment]
Workflow:
https://github.com/hdl/conda-eda/blob/master/.github/workflows/build-packages.yml#L768

Conda recipe:
https://github.com/hdl/conda-eda/blob/master/misc/open_pdks/meta.yaml

Conda build script:
https://github.com/hdl/conda-eda/blob/master/misc/open_pdks/build.sh

**Comment by donn** [comment]
Some notes:
* I need to be able to index the package by commit hash. We don't do versions over in OpenLane land.
* The default build needs to include SRAM.
* We need capacity to add other "flavors" down the line, such a full PDK build.

**Comment by proppy** [comment]
> I need to be able to index the package by commit hash. We don't do versions over in OpenLane land.

The short version of the commit hash is in the archive name, see https://anaconda.org/LiteX-Hub/open_pdks.sky130a/files
`noarch/open_pdks.sky130a-1.0.303_0_g`**`05af1d0`**`-20220330_123635.tar.bz2`

> The default build needs to include SRAM.

Filed https://github.com/hdl/conda-eda/issues/203

> We need capacity to add other "flavors" down the line, such a full PDK build.

We should be able to add subpackages of `open_pdks.sky130a`, ex: `open_pdks.sky130a.full` and build them from the same recipe: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#outputs-section

**Comment by proppy** [comment]
@donn how big is the open_pdks sram install? @mithro was concerned about the package size.

**Comment by donn** [comment]
xz compressed, the whole thing's about 177 megabytes.

**Comment by donn** [comment]
Given that we now also build the full PDK and allow users to download the PDK on a library-by-library basis, I don't think this is going to be entirely feasible anymore. :(

That being said, GitHub is not scaling very well for release storage. We may investigate other storage media in the future.
