### ISSUE TITLE
Pcell error for klayout in sky130A pdk

### ISSUE THREAD

**Issue by engrvip123** [efabless/volare#48]
Hi @donn  

Several of the klayout pcells for sky130 pdk sourced from **`$PDK_ROOT/$PDK/libs.tech/klayout/pymacros/cells`** gives error in klayout during instantiation. This is shown in attached screenshot. Can you please see if these klayout pcells can be updated so that complex layouts with sky130 pdk can be done using KLAYOUT.

![image (2)](https://github.com/efabless/volare/assets/115915095/bb0a01d5-059f-4c8d-baa4-e4b27a92aaeb)
![image (1)](https://github.com/efabless/volare/assets/115915095/ffc5b9a6-0286-4e57-b7b6-52cb0144699d)

**Comment by donn** [comment]
What is the exact PDK version you're using?

**Comment by engrvip123** [comment]
PDK version captured in screenshot
![image](https://github.com/efabless/volare/assets/115915095/d9037519-ce05-4135-b715-b18014672dae)

**Comment by donn** [comment]
If the issue persists, can you re-open this issue at https://github.com/rtimothyedwards/open_pdks? Thanks
