### ISSUE TITLE
volare might be shipping AGPL files?

### ISSUE THREAD

**Issue by mithro** [efabless/volare#66]
It seems like volare might be shipping some AGPL files in some way?

See for example https://foss-eda-tools.git.corp.google.com/third_party/shuttle/sky130/mpw-008/slot-027/+/HEAD/dependencies/pdks/volare/sky130/versions/0059588eebfc704681dc2368bd1d33d96281d10f/sky130A/libs.tech/klayout/lvs/run_lvs.py which seems to come from https://github.com/efabless/volare/releases/tag/sky130-0059588eebfc704681dc2368bd1d33d96281d10f ?

**Comment by mithro** [comment]
FYI - @mkkassem

**Comment by donn** [comment]
"# Copyright 2022 Efabless Cooperation" yeah there's more than just the license wrong with this file

**Comment by donn** [comment]
@RTimothyEdwards Where is this file pulled from?

**Comment by donn** [comment]
Tracked it down to https://github.com/efabless/sky130_klayout_pdk. We're investigating further.

**Comment by donn** [comment]
I've replaced all of these in sky130. Manually.

FWIW, the license does not actually apply to these files. It was an honest mistake by a contractor.
