### ISSUE TITLE
Please add a way to specify the verify= argument to httpx.Client

### ISSUE THREAD

**Issue by fisherdog3** [efabless/volare#87]
### Description

If a non-standard certificate is needed, eg on a corporate network, volare will not work. Reports not connected to the internet with ls-remote. Httpx does not seem to care about the system SSL certs in the usual search dirs but I could be mistaken. Other software which would be affected, conda and pip, do not have any issue connecting as I have installed the required cert. I was able to workaround by rebuilding with the verify= argument in the Client constructor.

### Expected Behavior

Should perform an ls-remote

### Relevant command

```shell-script
volare ls-remote
```

### Relevant log output

```shell-script
You don't appear to be connected to the Internet. ls-remote cannot be used.
```

**Comment by fisherdog3** [comment]
Supporting my claim that HTTPX is not using my certs:
https://github.com/encode/httpx/issues/302

**Comment by donn** [comment]
That would've been a nightmare to implement so what I did was: You can now `pip3 install volare[truststore]` which will use your computer's trust store.

**Comment by donn** [comment]
Can you confirm this works for you?

**Comment by fisherdog3** [comment]
This is working for me and I can ls-remote right after install.

**Comment by donn** [comment]
Glad to hear! Feel free to open another issue if you run into anything else. :)
